### PR TITLE
Web Teaster

### PR DESCRIPTION
**Pull request by ranchodhamala11**

### CODE REVIEW

**Comment by nnposter** [comment]
Looks like a PR misfire

**Comment by adfoster-r7** [comment]
@nnposter I believe it's hacktoberfest spam, we just received a similar pull request. If you mark the pull request as `spam` or `invalid`, it will disqualify this PR for them:


> If a repository maintainer decides a pull request you made was spammy or an unhelpful contribution to the project, they can add an invalid or spam label to your PR. This lets us know they do not think your pull request is a quality contribution, so it will not count toward Hacktoberfest.
> - https://hacktoberfest.digitalocean.com/faq

**Comment by nnposter** [comment]
@adfoster-r7 A great tip!

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Pull request closed without merging**
