### PR TITLE
Replace deprecated CPEs for Microsoft IIS. #2401

### LINKED ISSUE #2401: Deprecated CPEs for Microsoft IIS
Nmap detects Microsoft IIS as `cpe:/a:microsoft:internet_information_server`.

This has been deprecated and replaced with `cpe:/a:microsoft:internet_information_services` with the correct name of the product.

Sources include:
- IIS - https://nvd.nist.gov/products/cpe/detail/834795
- IIS 1.0 https://nvd.nist.gov/products/cpe/detail/834796
- ...
- IIS 7.0 https://nvd.nist.gov/products/cpe/detail/834802
- IIS 7.5 https://nvd.nist.gov/products/cpe/detail/126703
- IIS 8.0 https://nvd.nist.gov/products/cpe/detail/834804
- IIS 8.5 https://nvd.nist.gov/products/cpe/detail/393414
- IIS 10.0 https://nvd.nist.gov/products/cpe/detail/367120

### PR DESCRIPTION
**Pull request by oh2fih**
Replaces all `cpe:/a:microsoft:internet_information_server` with `cpe:/a:microsoft:internet_information_services` in Nmap service probes.

Closes #2401

### CODE REVIEW

**Comment by nnposter** [comment]
@dmiller-nmap I have noticed that this PR was merged directly, instead of imported into SVN. The SVN, currently at r38312, does not have the corresponding change. Does it mean that the GitHub repo is now the master?

**Comment by oh2fih** [comment]
I was wondering the same. According to CONTRIBUTING.md, GitHub should be used for pull requests. The changes are manually added to the Subversion repository and synced back from there. However, the document also states that the GitHub repository should be read only.

In my opinion the documented workflow seems a bit laborious, and it also hides all the people contributing to the project, so I hope this is not just a mistake, but a new beginning.

**Comment by dmiller-nmap** [comment]
Unfortunately, I just made a mistake in doing it this way. We're still not set up to make commits directly to Github. I'll have to clobber this one in order to allow SVN to sync again, then make a separate commit to SVN with a credit in the CHANGELOG for @oh2fih.

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Review by Aeshel12 — APPROVED** [review]

**Pull request merged**
