### PR TITLE
Support decimal-IP notation for 0.0.0.0 in Ncat

### PR DESCRIPTION
**Pull request by Varunram**
Solves a specific case of #375

### CODE REVIEW

**Comment by dmiller-nmap** [comment]
This is a bit too specific. We need to avoid the error condition, not introduce a new exception, since `getaddrinfo` handles numeric IP addresses just fine. See the updated comment on #375.

**Comment by Varunram** [comment]
Yeah, sounds like a cool idea. Since fyodor suggested that people might not use decimal addresses that frequently (except for 0.0.0.0), I thought I'd patch it up. I'll modify it to handle the general case.

**Comment by dmiller-nmap** [comment]
Closing this; open a new one if you come up with a general solution. Thanks!

**Comment by Varunram** [comment]
Have it on a branch, will rebase on master and open up a new PR soon

**Pull request closed without merging**
