### PR TITLE
Replaced goto with equivalent looping statements

### PR DESCRIPTION
**Pull request by shikharsrivastava**
This PR is keeping in mind the general coding principles to minimise use of goto statements. I have replaced the goto statements with equivalent looping statements keeping the same flow of control.

### CODE REVIEW

**Comment by Varunram** [comment]
@shikharsrivastava It does not maintain the same flow of control. You're replacing goto with an infinite loop which cannot exit under any circumstance

**Comment by shikharsrivastava** [comment]
@Varunram The orginal goto statement were itself acting as an infinite loop. The return statement at the end of the loop acts as exit.

**Comment by Varunram** [comment]
@shikharsrivastava Yeah identified that

**Comment by shikharsrivastava** [comment]
@dmiller-nmap Waiting for your review. There are some other files that can be updated siimilarly, I'll do it once this is reviewed.

**Comment by dmiller-nmap** [comment]
Thanks @shikharsrivastava and @capt2101akash for your concern over our code quality as indicated by number of `goto` statements. Far be it from me to argue with the eminent Edsger Dijkstra who so famously penned "Go To Statement Considered Harmful" (_Communications of the ACM_, Vol. 11, No. 3, March 1968.) I would, however, point you to [a modern annotation of his letter](http://david.tribble.com/text/goto.html), since the original predates the very language this code was written in (C, originally) by 7 years.

The essential point is this: the code in question is not an "unbridled use of the go to statement," nor is the use of it particularly "dense" as compared to other more modern structured programming control flow operators like `if`, `for`, `while`, and `switch`. We avoid the particular problems Dijkstra warns about involving difficulty keeping track of program progress by limiting `goto`s to the same scope as the label they point to. All but one of these instances are jumps forward to simple "clean up and return" blocks, where the state changes introduced (or not) by intervening lines are not relevant. The one case where a `goto` is used in place of a `while(true)`/`continue` loop, the label name (`try_again`) makes it clear that the original intent is a single pass through the function. My personal feeling is that the use of `return` within an infinite loop is at least as confusing as the `goto` it replaces.

Further reading: Donald Knuth (1974). ["Structured Programming With `go to` Statements"](https://www.cs.sjsu.edu/~mak/CS185C/KnuthStructuredProgrammingGoTo.pdf). Computing Surveys. 6 (4): 261–301.

P.S. The files in `liblua` are not the Nmap Project's own code, but are included for the convenience of users compiling the source. We do not accept patches for this code, but patches may be sent to [the Lua language developers](https://www.lua.org/community.html) for their consideration.

**Comment by shikharsrivastava** [comment]
Thanks a lot for the advice and valuable information you provided. I'll
keep this in mind in further works.

Regards
Shikhar Srivastava

**Comment by capt2101akash** [comment]
Thanks for giving information regarding this Daniel. It's really a helpful information for our future works. We will keep that in mind.

**Pull request closed without merging**
