### PR TITLE
Fix URL in HACKING

### PR DESCRIPTION
**Pull request by lgommans**
It's github.com, not github.org.

### CODE REVIEW

**Comment by fgeek** [comment]
:+1:

**Comment by cldrn** [comment]
Fixed in r36433, thanks!

**Comment by niloytanvir566-code** [comment]
mdmannan1983z@gmail.com i need this device live budy movment activities, Live location, call list,device audio recording

**Review by niloytanvir566-code — COMMENTED** [review]
Camara access

**Pull request closed without merging**
