### PR TITLE
Adding fingerprints for Netscaler, ActiveMQ, Purestorage

### PR DESCRIPTION
**Pull request by fitzpr**
Added lua fingerprints for Citrix Netscaler (portal for loadbalancers), ActiveMQ (portal for managing message queues) and Purestorage (portal for flash storage arrays)

### CODE REVIEW

**Comment by cldrn** [comment]
Thanks for this patch! I will add it to the database.

**Comment by cldrn** [comment]
Did you have any problem with our existing signature for citrix netscaler? I merged the other two signatures but I would like to know if there is a reason for writing another citrix netscaler signature.

**Comment by unexpectedindent** [comment]
Nothing came up when I scanned initially. I added the code I had for nsroot and it worked... Could be path related?

**Comment by cldrn** [comment]
Do you still have access to the device? Can you test and update the existing signature?

**Comment by unexpectedindent** [comment]
Sorry I don't seem to.

I totally missed the fact there was an existing signature for netscalers
sorry. I can only guess it was the ""<title>citrix login</title>"" that was
different and so nothing was found for my initial scans.

If i manage to get access to more devices I'll confirm.

Thanks

**Pull request closed without merging**
