### PR TITLE
new NSE script broadcast-sonicwall-discover

### PR DESCRIPTION
**Pull request by pfuender**
Hi Guys,

I've got a new script for you! It discovers a locally attached Sonicwall-firewall and prints some details about it. Find an example output right here:
```
| broadcast-sonicwall-discover: 
|   MAC/Serial: 0006B1001122
|   IP Address: 192.168.5.1
|   Subnetmask: 255.255.255.0
|   Firmware: 3.9.1.2
|_  ROM: 14.0.1.1
```

Let me know if you should have any questions - and else, thanks for merging! ;-)

Cheers
Pfuender

### CODE REVIEW

**Comment by ryanchou1991** [comment]
:+1:

**Comment by pfuender** [comment]
Any chance on getting this merged, or are there modifications needed from my side in order to do so? Thanks!

**Comment by dmiller-nmap** [comment]
@pfuender I'm sorry it has taken so long to get back on this. I've made a few changes to the way data is unpacked and reported, but since I don't have a sonicwall available for testing, I'd appreciate your feedback. A little back-and-forth and I'm confident we can get this included in Nmap. I've uploaded my changed version here: https://gist.github.com/dmiller-nmap/cf4f21c99300e615ce90

**Comment by pfuender** [comment]
@dmiller-nmap No worries! Thanks for the proposal, I quickly fixed the lines for Rom and Firmware version, as well as for the modified output. So far everything looks fine. 
https://gist.github.com/pfuender/f5487ae09b7427211c10

**Pull request closed without merging**
