### PR TITLE
Update http-fingerprints.lua

### PR DESCRIPTION
**Pull request by rvrsh3ll**
Corrected default OSGI admin portal location

### CODE REVIEW

**Comment by cldrn** [comment]
A better 'fix' would be to add the match instead of deleting the Adobe one. Multiple matches are supported so this shouldn't be a problem.

**Comment by rvrsh3ll** [comment]
Well, the /lc directory was a proprietary directory in one situation. /system/console is default

**Comment by cldrn** [comment]
So /lc/ isn't the default installation path for that software? then yeah, let's remove it.

**Comment by rvrsh3ll** [comment]
Correct

**Pull request closed without merging**
