### PR TITLE
Mitigate nil values and change strjoin library

### PR DESCRIPTION
**Pull request by vanjo9800**
The `msrpc.lua` and `msrpctypes.lua` were giving off errors when running the command:
`nmap -Pn -p445 --script smb-brute domain.com -d`.

The errors in the `msrpctypes.lua` script came from the migration from bin.pack and bin.unpack to string.pack and string.unpack. The former accepted `nil` values for as arguments and we did not do any arithmetic to determine whether the data is enough to extract an object. Now, however, we need to manually check whether the data is enough and can no longer pass `nil` values as arguments. The fix just initializes uninitialized variables to 1 which is the default for Lua.

The errros in the `msrpc.lua` script came from the wrong library referencing for the strjoin method used in some internal methods. I managed to find it in the `stringaux` library, not in the `stdnse`.

### CODE REVIEW

**Comment by nnposter** [comment]
Your patch for the stale references to `stdnse.strjoin` in library `msrpc` has been committed as r37721.

**Comment by nnposter** [comment]
The issue of arithmetic on a potentially nil `pos` argument is a bit more widespread throughout the `msrpctypes` library. A patch committed as r37722.

**Comment by nnposter** [comment]
The fix for ID Authority possibly being nil seems incorrect. See commit r37724 (ef2825b3bc6d7f8ecf0897ea1c3b0d13261e24b8) for an alternate assessment.

**Comment by vanjo9800** [comment]
Okay, thanks a lot for the fast response to the changes!
I will keep an eye for more issues.

**Comment by nnposter** [comment]
Thank your for finding the bugs and submitting patches. They are definitely appreciated.

I will tentatively close this issue; we can always reopen it later.

**Pull request closed without merging**
