### PR TITLE
Use creds from afp-brute in afp-*

### PR DESCRIPTION
**Pull request by Varunram**
Added reference to afp-brute credentials from all afp script except afp-serverinfo. Solves #650

### CODE REVIEW

**Comment by dmiller-nmap** [comment]
@Varunram Thanks for taking this on! This is a good start. There are a couple requirements that I didn't point out (a hazard of being to used to just writing code and not explaining it well, sorry!):

* The documentation should reflect the new way of passing credentials on the command line. If you remove the `afp.username` and `afp.password` script args, then the [NSEdoc](https://nmap.org/book/nsedoc.html) should be updated to show that.
* An empty password should be displayed as "<empty>" but stored as "" (the empty string).

Thankfully, there's a simple way to handle pretty much all of this: use the [`brute` library](https://nmap.org/nsedoc/lib/brute.html). Simply modifying `afp-brute` to follow the structure of e.g. [`redis-brute`](https://nmap.org/nsedoc/scripts/redis-brute.html) will take care of adding credentials, lots of timing tricks, and the "<empty>" password storage/display problem. All that would be left would be updating the NSEdoc. The `creds` library handles returning user-supplied creds along with script-discovered ones, so no worries there.

Check out `redis-brute` and `redis-info` for a simple set of scripts that use `brute` and `creds` to store and retrieve credentials. Another example would be `rpcap-brute` and `rpcap-info`. Looking forward to seeing an update!

**Comment by Varunram** [comment]
@dmiller-nmap Using brute would require of us to define a Driver class right?

**Comment by dmiller-nmap** [comment]
@Varunram That's correct. I think redis is password-only (no username), so that might not be the best example; `rlogin-brute` does username and password guessing with a socket connection, so maybe look at that one, too.

**Comment by Varunram** [comment]
@dmiller-nmap Did a few changes, but I think there might be a problem in the login function of the Driver class

**Comment by Varunram** [comment]
@dmiller-nmap Please review

**Pull request closed without merging**
