### PR TITLE
Updated the defaultBlacklist in httpspider.lua

### PR DESCRIPTION
**Pull request by rewanth1997**
Updated the list of extensions in addDefaultBlacklist in httpspider.lua.

References: wikipedia.

### CODE REVIEW

**Comment by dmiller-nmap** [comment]
This looks good, but please add a comment stating the source of these extensions. This will make it easier to update them in the future if need be.

**Comment by rewanth1997** [comment]
Image file formats: https://en.wikipedia.org/wiki/Image_file_formats
Video file formats: https://en.wikipedia.org/wiki/Video_file_format
Audio file formats: https://en.wikipedia.org/wiki/Audio_file_format
Doc file extension: https://en.wikipedia.org/wiki/List_of_Microsoft_Office_filename_extensions
Archive formats:    https://en.wikipedia.org/wiki/List_of_archive_formats

I have used these as my reference links for updating the data and picked up the most widely used extensions only. Some of the extensions mentioned in these references are completely obsoleted and hence I ignored those file extensions.

**Comment by dmiller-nmap** [comment]
This looks good; go ahead and commit to SVN. Be sure to put "Closes #860" in the commit message.

**Comment by nnposter** [comment]
From the commit:
```diff
+      image_extensions = {"png", "jpg", "jpeg", "gif", "bmp", "jfif", "exif",
+      "tiff", "bmp", "ppm", "pgm", "pbm", "pnm", "webp", "heif", "bat", "bpg",
+      "cgm", "svg"},
```
Should `bat` be really treated as an image extension?

**Comment by rewanth1997** [comment]
I also didn't find any image with bat extension, but I had added it to the list based on this reference, https://en.wikipedia.org/wiki/Image_file_formats#BAT

**Comment by nnposter** [comment]
My interpretation of the Wikipedia page is that it lists *formats*, not file *extensions* associated with such formats.

Considering the importance of interpreting the .bat extension reasonably by NSE, I would propose to drop it from the image list. (I would have proposed the same even if there was some evidence that the extension is sporadically being used for images.)

@dmiller-nmap Thoughts?

**Comment by rewanth1997** [comment]
I agree with nnposter @dmiller-nmap

**Comment by dmiller-nmap** [comment]
Yes, remove .bat from this list. The emphasis should be on reducing the
load on NSE by eliminating *likely* image file extensions. It is less
important to be exhaustive, especially when there is ambiguity.

**Pull request closed without merging**
