### PR TITLE
Working towards dual python2/python3 support.

### PR DESCRIPTION
**Pull request by eli-schwartz**
This patch series implements an incremental move to python3 in the nmap codebase. All changes should continue to work in python2, but improve the compatibility with python3.

Currently, I've mostly upgraded old-style python2 code that does not work on python3, to new-style python2 code that also works on python3; these changes are "the correct way" to do something on both python2 and python3, and thus have value even in an exclusively python2 codebase (but obviously python3 is important. ;))

The last patch adds additional compatibility shims only needed on python3 by using https://pypi.org/project/six/. Once python3 support is complete and python2 is dropped, `six.*` imports can be converted to their canonical python3 representations instead.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Ping. Any update on merging this?

**Comment by fyodor** [comment]
Hi @eli-schwartz .  Thanks for the patch.  I just made a note of it in issue #1176 .  Have you been able to successfully use Zenmap on a python3-only system with this patch?  I was under the impression that we would need a more fundamental overhaul because I thought some of our libraries (pygtk in particular, if I recall) wouldn't work with Python3.

**Comment by eli-schwartz** [comment]
I haven't tried running it in python3 yet, but I'm a big believer in baby steps. :)

First things first, let's get the codebase into a healthy place where hopefully the only thing that is left to port is pygtk usage itself.

I've revised my patch series, by the way, adding some more future imports and fixing a division error that cropped up as a result. I can run or load scans on python2, so it should work as is.

Also https://github.com/nmap/nmap/commit/ff357f96603f80da7c4fbe6a364aa6fc7e61b9de is just weird and broken right now.

**Comment by eli-schwartz** [comment]
Rolled back the unicode_literals change as I found more places where pygtk is oddly finicky about using the native `str()` type. The main identified benefit of unicode_literals in this codebase was making io.StringIO work nicely... pygtk strings will need to fend for themselves for now, hopefully they don't have broken escapes like the ndiff line.

**Pull request closed without merging**
