### PR TITLE
Check throttling of connections

### PR DESCRIPTION
**Pull request by Varunram**
Solves #654 In case of connection throttling, connection is avoided.

### CODE REVIEW

**Comment by dmiller-nmap** [comment]
This does not change anything: if `status` is true, `response` will not be an error and so will not have an `isReduce()` method. We need to check `isReduce` when `status` is false, then take some action. Not sure what that action is, but I'm guessing it's a return to end that particular thread.

**Comment by Varunram** [comment]
Ah my bad, will correct that

**Comment by Varunram** [comment]
@dmiller-nmap Made the changes

**Comment by Varunram** [comment]
@dmiller-nmap Please review this one too

**Pull request closed without merging**
