### PR TITLE
http-default-accounts-fingerprints: Tomcat, add support for host-manager

### PR DESCRIPTION
**Pull request by cnotin**
Tomcat has two common management applications: "manager" and "host-manager".
Host manager is at "/host-manager/html" and with the "Tomcat Host Manager Application" realm.
See:
https://github.com/apache/tomcat/blob/3e5ce3108e2684bc25013d9a84a7966a6dcd6e14/webapps/manager/WEB-INF/web.xml#L153
https://github.com/apache/tomcat/blob/3e5ce3108e2684bc25013d9a84a7966a6dcd6e14/webapps/host-manager/WEB-INF/web.xml#L99

### CODE REVIEW

**Comment by cnotin** [comment]
Thanks for the detailed feedback. Indeed it's better this way!
I see that you made it that way in your repo, do you intend to change it here too, or how do you suggest we proceed? Should I update my PR?

**Comment by nnposter** [comment]
My fingerprint set is not a working clone of what is in Nmap but a separate, GPL-licensed product, which makes it unsuitable for merging into Nmap. I would suggest two paths forward:

* Either keep the current single-fingerprint design and just add the missing path of `/tomcat/host-manager/html/`.
* Or, split the fingerprint as discussed and update the PR. (Again, for licensing reasons you cannot just copy my code.)

I am fine with either approach.

**Comment by cnotin** [comment]
I split the fingerprint since it's better as you said.
I also added a few URLs for manager as shown in https://github.com/apache/tomcat/blob/master/webapps/manager/WEB-INF/web.xml

I copied the credential for "host manager" from "manager". I did not copy your own.

**Comment by nnposter** [comment]
Committed as r37772. Thank you for contributing to Nmap!

**Comment by cnotin** [comment]
Thanks for suggestions!

**Pull request closed without merging**
